services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  gateway:
    build: ./gateway
    volumes:
      - ./data:/data
    depends_on:
      - mqtt
    deploy:
      replicas: 3
    environment:
      - CLOUD_ENDPOINT=${CLOUD_ENDPOINT:-http://host.docker.internal:7071/api/iot-data}
      - BATCH_SIZE=${BATCH_SIZE:-100}
      - SEND_INTERVAL=${SEND_INTERVAL:-5}

  device:
    build: ./device-simulator
    deploy:
      replicas: 100
    environment:
      - MQTT_BROKER=mqtt

