version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  gateway:
    build: ./gateway
    volumes:
      - ./data:/data
    depends_on:
      - mqtt
    environment:
      - CLOUD_ENDPOINT=${CLOUD_ENDPOINT:-http://host.docker.internal:7071/api/iot-data}
      - BATCH_SIZE=${BATCH_SIZE:-10}
      - SEND_INTERVAL=${SEND_INTERVAL:-30}

  device:
    build: ./device-simulator
    depends_on:
      - mqtt

